### PR TITLE
chore: increase sidebar width

### PR DESCRIPTION
**Pull request by maxigimenez**

### CODE REVIEW

**Comment by maxigimenez** [comment]
@tnolet still centered, but could be a bit confusing with the navigation on the right 

Screenshot 2020-08-11 at 11 32 00

**Comment by tnolet** [comment]
> @tnolet still centered, but could be a bit confusing with the navigation on the right
> 
> Screenshot 2020-08-11 at 11 32 00

I think I mean centered on the screen, not in the panel. Have a look at https://stripe.com/docs/connect for example

**Comment by maxigimenez** [comment]
@tnolet hmm, stripe content is not centered, also these changes shouldn't affect the position of the content

Screenshot 2020-08-11 at 11 46 28

**Comment by tnolet** [comment]
We agreed tot tackle the centering separately from this PR

**Pull request merged**
